version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6udojmp2uwop"
s3_prefix = "sam-hello-world"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
